# Generated by Django 3.2.7 on 2021-10-15 14:53

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaModel',
            fields=[
                ('marcaId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('marcaNombre', models.CharField(db_column='nombre', max_length=100)),
                ('marcaDescripcion', models.TextField(null=True)),
            ],
            options={
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('usuarioId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('usuarioDni', models.CharField(db_column='dni', max_length=8)),
                ('usuarioNombre', models.CharField(db_column='nombre', max_length=50)),
                ('usuarioApellido', models.CharField(db_column='apellido', max_length=50, verbose_name='Apellido del usuario')),
                ('usuarioCorreo', models.EmailField(db_column='email', max_length=50, unique=True)),
                ('usuarioTipo', models.IntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'MANTENEDOR'), (3, 'CLIENTE')], db_column='tipo')),
                ('password', models.TextField(null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('productoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('productoNombre', models.CharField(db_column='nombre', max_length=100)),
                ('productoPrecio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=5)),
                ('productoFoto', models.CharField(db_column='foto', max_length=130, null=True)),
                ('productoCantidad', models.IntegerField(db_column='cantidad', validators=[django.core.validators.MinValueValidator(0, 'Valor no puede ser negativo')])),
                ('prodoductoTalla', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), db_column='talla', size=None), size=None)),
                ('productoActualizado', models.DateTimeField(auto_now_add=True, db_column='updated_at')),
                ('productoCreado', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('marca', models.ForeignKey(db_column='marca_id', on_delete=django.db.models.deletion.PROTECT, related_name='marcaProducto', to='manejoEc.marcamodel')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
