# Generated by Django 3.2.7 on 2021-10-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manejoEc', '0001_migracion_init'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productomodel',
            old_name='prodoductoTalla',
            new_name='productoTalla',
        ),
    ]
