# Generated by Django 3.2.7 on 2021-10-16 03:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manejoEc', '0001_migracion_init'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoModel',
            fields=[
                ('pedidoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('pedidoFecha', models.DateTimeField(auto_now_add=True, db_column='fecha')),
                ('pedidoTotal', models.DecimalField(db_column='total', decimal_places=2, max_digits=5)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='clientePedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoModel',
            fields=[
                ('detalleId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('detalleCantidad', models.IntegerField(db_column='cantidad', validators=[django.core.validators.MinValueValidator(0, 'Valor no puede ser negativo')])),
                ('detalleSubTotal', models.DecimalField(db_column='sub_total', decimal_places=2, max_digits=5)),
                ('pedido', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.PROTECT, related_name='pedidoDetalles', to='manejoEc.pedidomodel')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='productoDetalles', to='manejoEc.productomodel')),
            ],
            options={
                'db_table': 'detalles',
            },
        ),
    ]
