# Generated by Django 3.2.7 on 2021-10-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejoEc', '0002_migracion_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidomodel',
            name='detalleSubTotal',
            field=models.DecimalField(db_column='sub_total', decimal_places=2, max_digits=7),
        ),
    ]
