name: workflow-pull-request
on:
  pull_request:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    
    steps:
      - name: Validar el repositorio
        uses: actions/checkout@v2

      - name: Validar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.6"
          architecture: "x64"

      - name: Instalar librerias
        run: pip3 install -r requirements.txt

      - name: Correr los Tests
        run: python3 manage.py test 
