name: workflow-pull-request
on:
  pull_request:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      DB_TEST: DB_TEST
      DB_HOST: DB_HOST
      DB_USER: DB_USER
      DB_PASSWORD: DB_PASSWORD
      DB_NAME: DB_NAME
      DB_PORT: 5432
      
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: DB_USER
          POSTGRES_PASSWORD: DB_PASSWORD
          POSTGRES_DB: DB_TEST
          POSTGRES_PORT: 5432
          POSTGRES_HOST: DB_HOST
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    
    steps:
      - name: Validar el repositorio
        uses: actions/checkout@v2

      - name: Validar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.6"
          architecture: "x64"

      - name: Instalar librerias
        run: pip3 install -r requirements.txt

      - name: Correr los Tests
        run: python3 manage.py test 
