name: workflow-pull-request
on:
  pull_request:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      DB_TEST: ${{ secrets.DB_NAME }}
      
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_PORT: ${{ secrets.DB_PORT }}
          POSTGRES_HOST: ${{ secrets.DB_HOST }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    
    steps:
      - name: Validar el repositorio
        uses: actions/checkout@v2

      - name: Validar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.6"
          architecture: "x64"

      - name: Instalar librerias
        run: pip3 install -r requirements.txt

      - name: Correr los Tests
        run: python3 manage.py test 
